name: neaws
description:
    A news reader for Android and iOS written in Flutter. Uses newsapi.org.

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    cached_network_image: ^2.0.0-rc.1

    dio: ^3.0.10

    eva_icons_flutter: ^2.0.1

    flutter:
        sdk: flutter

    flutter_custom_tabs: ^0.6.0

    provider: ^4.3.3

    share: ^0.6.5

    shared_preferences: ^0.5.12

    simple_design: ^1.0.3

dev_dependencies:
    flutter_launcher_icons: ^0.7.5

    flutter_test:
        sdk: flutter

    lint: ^1.5.3

flutter_icons:
    android: true
    ios: false
    image_path: "assets/logo.png"

flutter:
    uses-material-design: true

    fonts:
        - family: HK Grotesk
          fonts:
              - asset: fonts/Inter-Light-BETA.ttf
              - asset: fonts/Inter-Bold.ttf
                weight: 700
