name: neaws
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: '>=2.1.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    dio: ^3.0.7

    flutter_custom_tabs: ^0.6.0

    shared_preferences: ^0.5.6

    simple_design: ^1.0.3

    eva_icons_flutter: ^2.0.0

    cached_network_image: ^2.0.0-rc.1

    share: ^0.6.3+5

    provider: ^3.2.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.7.4

flutter_icons:
    android: true
    ios: false
    image_path: 'assets/logo.png'

flutter:
    uses-material-design: true

    fonts:
        - family: HK Grotesk
          fonts:
              - asset: fonts/Inter-Light-BETA.ttf
              - asset: fonts/Inter-Bold.ttf
                weight: 700
